### ISSUE TITLE
Firefox or Chrome starts always in same Monitor, whether if monitor is set to 1 or 2

### ISSUE THREAD

**Issue by wtuz** [SuperflyJon/FileStarter#5]
[

	{
		"desktop": 1,
		"process": "firefox",
		"monitor": 2,
		"hassplash": true
	}

]

**Comment by SuperflyJon** [comment]
This worked for me, using Chrome:

[
 {
  "desktop":"1",
  "process":"chrome",
  "monitor":"2",
  "state":"max",
  "waitForClass":"Chrome_WidgetWin_1"
 }
]

This was on windows 10 - are you using windows 11?

**Comment by wtuz** [comment]
using Windows 10 Enterprise , Version 21H2

**Comment by SuperflyJon** [comment]
This still works okay for me.  Must be something special on your machine and/or Chrome - maybe a special extension or something?

**Comment by SuperflyJon** [comment]
Note that the "waitForClass" line is needed: 
[
 {
  "process":"chrome",
  "monitor":1,
  "waitForClass":"Chrome_WidgetWin_1"
 }
]

**Comment by wtuz** [comment]
> Note that the "waitForClass" line is needed: [ { "process":"chrome", "monitor":1, "waitForClass":"Chrome_WidgetWin_1" } ]

can you show me, what i have to set for waitForClass for firefox?

**Comment by SuperflyJon** [comment]
I didn't have Firefox on my machine, so took a while...  You need:
    "waitForClass": "MozillaWindowClass"
